# Generated by Django 5.1.4 on 2024-12-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('IT', 'IT Sector'), ('ELE', 'Electrical & Electronic Sector'), ('PASSIVE', 'Passive Income Sector')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ElectricalResource',
        ),
        migrations.DeleteModel(
            name='ITResource',
        ),
        migrations.DeleteModel(
            name='PassiveIncomeResource',
        ),
    ]
